apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  labels:
    name: prometheus-node-exporter
    app: node-exporter
  annotations:
   prometheus.io/scrape: 'true'
spec:
  type: NodePort 
  ports:
  - port: 9100
    name: scrape
    protocol: TCP
    nodePort: 30001
  selector:
    app: node-exporter
